### ISSUE TITLE
Roadmap du projet

### ISSUE THREAD

**Issue by stephane-klein** [stephane-klein/epiclub-inscription#1]
- [x] Installer [Gatsby](https://www.gatsbyjs.org/)
- [x] Configurer [chakra-ui](https://github.com/chakra-ui/chakra-ui/)
- [ ] Créer un premier formulaire
- [ ] Configurer [react-hook-form](https://react-hook-form.com/)

**Comment by stephane-klein** [comment]
Je me suis basé sur https://www.gatsbyjs.org/packages/gatsby-plugin-chakra-ui/ pour initialiser chakra-ui dans Gatsby.

Le code source du thème est https://github.com/chakra-ui/chakra-ui/tree/master/tooling/gatsby-plugin-chakra-ui
